const bubbleChart = [
    { name: "flare", title: "flare", group: "analytics", value: 32980, color: 'blueviolet' },
    { name: "analytics", title: "flare/analytics", group: "analytics", value: 709, color: 'aliceblue' },
    { name: "cluster", title: "flare/analytics/cluster", group: "analytics", value: 500 , color: '#f7e98e'},
    { name: "AgglomerativeCluster", title: "flare/analytics/cluster/AgglomerativeCluster", group: "analytics", value: 3938, color: 'Indigo' },
    { name: "CommunityStructure", title: "flare/analytics/cluster/CommunityStructure", group: "analytics", value: 3812, color: 'Teal' },
    { name: "HierarchicalCluster", title: "flare/analytics/cluster/HierarchicalCluster", group: "analytics", value: 6714 , color: 'blanchedalmond'},
    { name: "MergeEdge", title: "flare/analytics/cluster/MergeEdge", group: "analytics", value: 743 , color: 'Violet'},
    { name: "graph", title: "flare/analytics/graph", group: "analytics", value: 3980, color: '#1e90ff' },
    { name: "BetweennessCentrality", title: "flare/analytics/graph/BetweennessCentrality", group: "analytics", value: 3534, color: '#4f86f7'},
    { name: "LinkDistance", title: "flare/analytics/graph/LinkDistance", group: "analytics", value: 5731, color: 'blueviolet'},
    { name: "MaxFlowMinCut", title: "flare/analytics/graph/MaxFlowMinCut", group: "analytics", value: 7840, color: 'brown'},
    { name: "ShortestPaths", title: "flare/analytics/graph/ShortestPaths", group: "analytics", value: 5914 , color: '#fbe96c'},
    { name: "SpanningTree", title: "flare/analytics/graph/SpanningTree", group: "analytics", value: 3416 , color: 'burlywood'},
    { name: "optimization", title: "flare/analytics/optimization", group: "analytics", value: 6789, color: "Silver"},
    { name: "AspectRatioBanker", title: "flare/analytics/optimization/AspectRatioBanker", group: "analytics", value: 7074 , color: 'chartreuse'},
    { name: "animate", title: "flare/animate", group: "animate", value: 4590, color: '#ba8759' },
    { name: "Easing", title: "flare/animate/Easing", group: "animate", value: 17010, color: '#00008b' },
    { name: "FunctionSequence", title: "flare/animate/FunctionSequence", group: "animate", value: 5842 , color: 'Purple'},
    { name: "interpolate", title: "flare/animate/interpolate", group: "animate", value: 200, color: 'Magenta'},
    { name: "ArrayInterpolator", title: "flare/animate/interpolate/ArrayInterpolator", group: "animate", value: 1983, color: '#cfb53b' },
    { name: "ColorInterpolator", title: "flare/animate/interpolate/ColorInterpolator", group: "animate", value: 2047, color: 'chocolate'},
    { name: "DateInterpolator", title: "flare/animate/interpolate/DateInterpolator", group: "animate", value: 1375, color: '#c04000'},
    { name: "Interpolator", title: "flare/animate/interpolate/Interpolator", group: "animate", value: 8746, color: 'green'},
    { name: "MatrixInterpolator", title: "flare/animate/interpolate/MatrixInterpolator", group: "animate", value: 2202, color: '#b05d54'},
    { name: "NumberInterpolator", title: "flare/animate/interpolate/NumberInterpolator", group: "animate", value: 1382, color: 'cadetblue' },
    { name: "PointInterpolator", title: "flare/animate/interpolate/PointInterpolator", group: "animate", value: 1675, color: 'blue' },
    { name: "RectangleInterpolator", title: "flare/animate/interpolate/RectangleInterpolator", group: "animate", value: 2042, color: 'Gold' },
    { name: "ISchedulable", title: "flare/animate/ISchedulable", group: "animate", value: 1041, color: '#c54b8c' },
    { name: "Parallel", title: "flare/animate/Parallel", group: "animate", value: 5176, color: 'Orange'},
    { name: "Pause", title: "flare/animate/Pause", group: "animate", value: 449, color: 'blanchedalmond'},
    { name: "Scheduler", title: "flare/animate/Scheduler", group: "animate", value: 5593, color: 'aliceblue' },
    { name: "Sequence", title: "flare/animate/Sequence", group: "animate", value: 5534, color: 'beige'},
    { name: "Transition", title: "flare/animate/Transition", group: "animate", value: 9201, color: 'bisque'},
    { name: "Transitioner", title: "flare/animate/Transitioner", group: "animate", value: 19975, color: 'coral' },
    { name: "TransitionEvent", title: "flare/animate/TransitionEvent", group: "animate", value: 1116, color: 'aquamarine'},
    { name: "Tween", title: "flare/animate/Tween", group: "animate", value: 6006, color: 'red'},
    { name: "data", title: "flare/data", group: "data", value: 200, color: '#9f00c5' },
    { name: "converters", title: "flare/data/converters", group: "data", value: 39801, color: 'antiquewhite'},
    { name: "Converters", title: "flare/data/converters/Converters", group: "data", value: 721, color: 'aqua' }
]


    export {bubbleChart}
    